productimporter:
    path: productimporter
    methods: [GET]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:indexAction'
      _legacy_controller: 'AdminProductImporter'
      _legacy_link: 'AdminProductImporter'
productimporter-config:
    path: productimporter/config
    methods: [GET, POST]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:configAction'
      _legacy_controller: 'AdminProductImporterSettings'
      _legacy_link: 'AdminProductImporterSettings'

productimporter-categories:
    path: productimporter/categories
    methods: [GET, POST]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:categoriesAction'
      _legacy_controller: 'AdminCategoryMapping'
      _legacy_link: 'AdminCategoryMapping'

productimporter-categories-link:
    path: productimporter/categories/link
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:categoriesActionLink'
    

# START Category CRUD

# Delete
productimporter-categories-delete:
    path: productimporter/categories/delete
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:categoriesActionDelete'

# Create category modal - Get parent categories 
productimporter-categories-get-parents:
    path: productimporter/categories/get-parents
    methods: [GET]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:categoriesActionGetParents'
    options:
        expose: true

# Create category modal - Create category
productimporter-categories-add:
    path: productimporter/categories/add
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoriesCrudController:categoriesActionCreate'
    options:
        expose: true

# Edit category modal - Edit category
productimporter-categories-edit:
    path: productimporter/categories/edit
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoriesCrudController:categoriesActionEdit'
    options:
        expose: true

# END Category CRUD


# START Category mapping operations

# Get local mapped categories
productimporter-get-local-mapped-categories:
    path: productimporter/categories/local-mapped
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoriesCrudController:categoriesActionGetLocalMapped'

# Get remote mapped categories
productimporter-get-remote-mapped-categories:
    path: productimporter/categories/remote-mapped
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoriesCrudController:categoriesActionGetRemoteMapped'

