productimporter:
    path: productimporter
    methods: [GET]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:indexAction'
      _legacy_controller: 'AdminProductImporter'
      _legacy_link: 'AdminProductImporter'
productimporter-config:
    path: productimporter/config
    methods: [GET, POST]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:configAction'
      _legacy_controller: 'AdminProductImporterSettings'
      _legacy_link: 'AdminProductImporterSettings'

productimporter-categories:
    path: productimporter/categories
    methods: [GET, POST]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:categoriesAction'
      _legacy_controller: 'AdminCategoryMapping'
      _legacy_link: 'AdminCategoryMapping'


# START Category CRUD

# Delete
productimporter-categories-delete:
    path: productimporter/categories/delete
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryCrudController:categoriesActionDelete'

# Create category modal - Get parent categories 
productimporter-categories-get-parents:
    path: productimporter/categories/get-parents
    methods: [GET]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryCrudController:categoriesActionGetParents'
    options:
        expose: true

# Create category modal - Create category
productimporter-categories-add:
    path: productimporter/categories/add
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryCrudController:categoriesActionCreate'
    options:
        expose: true

# Edit category modal - Edit category
productimporter-categories-edit:
    path: productimporter/categories/edit
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryCrudController:categoriesActionEdit'
    options:
        expose: true

# END Category CRUD


# START Category mapping operations

#Link category
productimporter-categories-link:
    path: productimporter/categories/link
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryActionsController:categoriesActionLink'
    
# Get local mapped categories
productimporter-get-local-mapped-categories:
    path: productimporter/categories/local-mapped
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryActionsController:categoriesActionGetLocalMapped'

# Get remote mapped categories
productimporter-get-remote-mapped-categories:
    path: productimporter/categories/remote-mapped
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryActionsController:categoriesActionGetRemoteMapped'

#Unlink category
productimporter-categories-unlink:
    path: productimporter/categories/unlink
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\CategoryActionsController:categoriesActionUnlink'


# END Category mapping operations



#EXTRAS
# Sync categories
productimporter-categories-sync:
    path: productimporter/categories/sync
    methods: [POST]
    defaults:
      _controller: 'ProductImporter\Controller\ProductImporterController:categoriesActionSync'


#Tree Initialization

productimporter-get-remote-category-tree:
    path: productimporter/categories/remote-tree
    methods: [GET]
    defaults:
      _controller: 'ProductImporter\Controller\TreeInitializationController:remoteCategoryTree'

productimporter-get-local-category-tree:
    path: productimporter/categories/local-tree
    methods: [GET]
    defaults:
      _controller: 'ProductImporter\Controller\TreeInitializationController:localCategoryTree'

